version: '3.8'

services:
  backend:
    container_name: trellis-law-test-backend
    build:
      context: ./trellis_law_test_backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:5173

  frontend:
    container_name: trellis-law-test-frontend
    build:
      context: ./trellis-law-test-frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
