name: Cypress tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          working-directory: trellis-law-test-frontend
