name: Backend CI - Django

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.8
      - name: Install Dependencies
        working-directory: trellis_law_test_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: trellis_law_test_backend.settings
          python_files: tests.py test_*.py *_tests.py
        run: |
          pytest
